version: "3.8"

services:
  mc:
    container_name: minecraft-server
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TYPE: FORGE
      EULA: "TRUE"
      VERSION: "1.20.1"
    volumes:
      - ./data:/data